#!/usr/bin/env python3
"""Turns defaults/patterns.txt and defaults/current.txt into
code/src/x0x/defaults.h, the patterns and settings a new card starts with.
Run it after changing either file: python3 defaults/make_header.py"""
import os

here = os.path.dirname(os.path.abspath(__file__))
out = os.path.join(here, '..', 'code', 'src', 'x0x', 'defaults.h')


def literal(name, path):
    text = open(path).read()
    lines = ''.join('    "%s\\n"\n' % line.replace('\\', '\\\\').replace('"', '\\"') for line in text.splitlines())
    return 'constexpr char %s[] =\n%s    "";\n' % (name, lines)


with open(out, 'w') as f:
    f.write('/** @file defaults.h\n'
            ' *  @brief The patterns and knob settings a new card starts with: when\n'
            ' *  /X0X/patterns.txt or current.txt is missing, these load instead (and\n'
            ' *  save to the card from then on). Generated by defaults/make_header.py\n'
            ' *  from defaults/patterns.txt and current.txt; edit those, not this.\n'
            ' */\n#pragma once\n\nnamespace x0x\n{\n\n')
    f.write(literal('kDefaultPatterns', os.path.join(here, 'patterns.txt')))
    f.write('\n')
    f.write(literal('kDefaultSettings', os.path.join(here, 'current.txt')))
    f.write('\n} // namespace x0x\n')
print('wrote', os.path.normpath(out))
